webtalk_init -webtalk_dir /home/quartus/Documents/TP/TP_0/mse_mandelbrot_no_bram/mse_mandelbrot.sim/sim_1/behav/xsim/xsim.dir/tb_fractal_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri May 11 19:52:49 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4763a836-6ec6-416b-8cd7-ec8a8207e635" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "48f417b18c744a1fab1dc15364498564" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "40" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 9.4 (stretch)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1866.369 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "24.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "128564_KB" -context "xsim\\usage"
webtalk_transmit -clientid 480676279 -regid "" -xml /home/quartus/Documents/TP/TP_0/mse_mandelbrot_no_bram/mse_mandelbrot.sim/sim_1/behav/xsim/xsim.dir/tb_fractal_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/quartus/Documents/TP/TP_0/mse_mandelbrot_no_bram/mse_mandelbrot.sim/sim_1/behav/xsim/xsim.dir/tb_fractal_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/quartus/Documents/TP/TP_0/mse_mandelbrot_no_bram/mse_mandelbrot.sim/sim_1/behav/xsim/xsim.dir/tb_fractal_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
